# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/embedded/exo_muscle_ws/src/libgp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/embedded/exo_muscle_ws/src/libgp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/embedded/exo_muscle_ws/src/libgp/CMakeFiles /home/embedded/exo_muscle_ws/src/libgp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/embedded/exo_muscle_ws/src/libgp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gp

# Build rule for target.
gp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gp
.PHONY : gp

# fast build rule for target.
gp/fast:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/build
.PHONY : gp/fast

#=============================================================================
# Target rules for targets named gp_calib

# Build rule for target.
gp_calib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gp_calib
.PHONY : gp_calib

# fast build rule for target.
gp_calib/fast:
	$(MAKE) -f examples/CMakeFiles/gp_calib.dir/build.make examples/CMakeFiles/gp_calib.dir/build
.PHONY : gp_calib/fast

#=============================================================================
# Target rules for targets named gpdense

# Build rule for target.
gpdense: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpdense
.PHONY : gpdense

# fast build rule for target.
gpdense/fast:
	$(MAKE) -f examples/CMakeFiles/gpdense.dir/build.make examples/CMakeFiles/gpdense.dir/build
.PHONY : gpdense/fast

#=============================================================================
# Target rules for targets named gptest

# Build rule for target.
gptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gptest
.PHONY : gptest

# fast build rule for target.
gptest/fast:
	$(MAKE) -f tests/CMakeFiles/gptest.dir/build.make tests/CMakeFiles/gptest.dir/build
.PHONY : gptest/fast

#=============================================================================
# Target rules for targets named googletest

# Build rule for target.
googletest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googletest
.PHONY : googletest

# fast build rule for target.
googletest/fast:
	$(MAKE) -f tests/CMakeFiles/googletest.dir/build.make tests/CMakeFiles/googletest.dir/build
.PHONY : googletest/fast

src/cg.o: src/cg.cc.o

.PHONY : src/cg.o

# target to build an object file
src/cg.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cg.cc.o
.PHONY : src/cg.cc.o

src/cg.i: src/cg.cc.i

.PHONY : src/cg.i

# target to preprocess a source file
src/cg.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cg.cc.i
.PHONY : src/cg.cc.i

src/cg.s: src/cg.cc.s

.PHONY : src/cg.s

# target to generate assembly for a file
src/cg.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cg.cc.s
.PHONY : src/cg.cc.s

src/cov.o: src/cov.cc.o

.PHONY : src/cov.o

# target to build an object file
src/cov.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov.cc.o
.PHONY : src/cov.cc.o

src/cov.i: src/cov.cc.i

.PHONY : src/cov.i

# target to preprocess a source file
src/cov.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov.cc.i
.PHONY : src/cov.cc.i

src/cov.s: src/cov.cc.s

.PHONY : src/cov.s

# target to generate assembly for a file
src/cov.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov.cc.s
.PHONY : src/cov.cc.s

src/cov_factory.o: src/cov_factory.cc.o

.PHONY : src/cov_factory.o

# target to build an object file
src/cov_factory.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_factory.cc.o
.PHONY : src/cov_factory.cc.o

src/cov_factory.i: src/cov_factory.cc.i

.PHONY : src/cov_factory.i

# target to preprocess a source file
src/cov_factory.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_factory.cc.i
.PHONY : src/cov_factory.cc.i

src/cov_factory.s: src/cov_factory.cc.s

.PHONY : src/cov_factory.s

# target to generate assembly for a file
src/cov_factory.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_factory.cc.s
.PHONY : src/cov_factory.cc.s

src/cov_linear_ard.o: src/cov_linear_ard.cc.o

.PHONY : src/cov_linear_ard.o

# target to build an object file
src/cov_linear_ard.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_ard.cc.o
.PHONY : src/cov_linear_ard.cc.o

src/cov_linear_ard.i: src/cov_linear_ard.cc.i

.PHONY : src/cov_linear_ard.i

# target to preprocess a source file
src/cov_linear_ard.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_ard.cc.i
.PHONY : src/cov_linear_ard.cc.i

src/cov_linear_ard.s: src/cov_linear_ard.cc.s

.PHONY : src/cov_linear_ard.s

# target to generate assembly for a file
src/cov_linear_ard.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_ard.cc.s
.PHONY : src/cov_linear_ard.cc.s

src/cov_linear_one.o: src/cov_linear_one.cc.o

.PHONY : src/cov_linear_one.o

# target to build an object file
src/cov_linear_one.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_one.cc.o
.PHONY : src/cov_linear_one.cc.o

src/cov_linear_one.i: src/cov_linear_one.cc.i

.PHONY : src/cov_linear_one.i

# target to preprocess a source file
src/cov_linear_one.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_one.cc.i
.PHONY : src/cov_linear_one.cc.i

src/cov_linear_one.s: src/cov_linear_one.cc.s

.PHONY : src/cov_linear_one.s

# target to generate assembly for a file
src/cov_linear_one.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_linear_one.cc.s
.PHONY : src/cov_linear_one.cc.s

src/cov_matern3_iso.o: src/cov_matern3_iso.cc.o

.PHONY : src/cov_matern3_iso.o

# target to build an object file
src/cov_matern3_iso.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern3_iso.cc.o
.PHONY : src/cov_matern3_iso.cc.o

src/cov_matern3_iso.i: src/cov_matern3_iso.cc.i

.PHONY : src/cov_matern3_iso.i

# target to preprocess a source file
src/cov_matern3_iso.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern3_iso.cc.i
.PHONY : src/cov_matern3_iso.cc.i

src/cov_matern3_iso.s: src/cov_matern3_iso.cc.s

.PHONY : src/cov_matern3_iso.s

# target to generate assembly for a file
src/cov_matern3_iso.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern3_iso.cc.s
.PHONY : src/cov_matern3_iso.cc.s

src/cov_matern5_iso.o: src/cov_matern5_iso.cc.o

.PHONY : src/cov_matern5_iso.o

# target to build an object file
src/cov_matern5_iso.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern5_iso.cc.o
.PHONY : src/cov_matern5_iso.cc.o

src/cov_matern5_iso.i: src/cov_matern5_iso.cc.i

.PHONY : src/cov_matern5_iso.i

# target to preprocess a source file
src/cov_matern5_iso.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern5_iso.cc.i
.PHONY : src/cov_matern5_iso.cc.i

src/cov_matern5_iso.s: src/cov_matern5_iso.cc.s

.PHONY : src/cov_matern5_iso.s

# target to generate assembly for a file
src/cov_matern5_iso.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_matern5_iso.cc.s
.PHONY : src/cov_matern5_iso.cc.s

src/cov_noise.o: src/cov_noise.cc.o

.PHONY : src/cov_noise.o

# target to build an object file
src/cov_noise.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_noise.cc.o
.PHONY : src/cov_noise.cc.o

src/cov_noise.i: src/cov_noise.cc.i

.PHONY : src/cov_noise.i

# target to preprocess a source file
src/cov_noise.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_noise.cc.i
.PHONY : src/cov_noise.cc.i

src/cov_noise.s: src/cov_noise.cc.s

.PHONY : src/cov_noise.s

# target to generate assembly for a file
src/cov_noise.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_noise.cc.s
.PHONY : src/cov_noise.cc.s

src/cov_periodic.o: src/cov_periodic.cc.o

.PHONY : src/cov_periodic.o

# target to build an object file
src/cov_periodic.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic.cc.o
.PHONY : src/cov_periodic.cc.o

src/cov_periodic.i: src/cov_periodic.cc.i

.PHONY : src/cov_periodic.i

# target to preprocess a source file
src/cov_periodic.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic.cc.i
.PHONY : src/cov_periodic.cc.i

src/cov_periodic.s: src/cov_periodic.cc.s

.PHONY : src/cov_periodic.s

# target to generate assembly for a file
src/cov_periodic.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic.cc.s
.PHONY : src/cov_periodic.cc.s

src/cov_periodic_matern3_iso.o: src/cov_periodic_matern3_iso.cc.o

.PHONY : src/cov_periodic_matern3_iso.o

# target to build an object file
src/cov_periodic_matern3_iso.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic_matern3_iso.cc.o
.PHONY : src/cov_periodic_matern3_iso.cc.o

src/cov_periodic_matern3_iso.i: src/cov_periodic_matern3_iso.cc.i

.PHONY : src/cov_periodic_matern3_iso.i

# target to preprocess a source file
src/cov_periodic_matern3_iso.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic_matern3_iso.cc.i
.PHONY : src/cov_periodic_matern3_iso.cc.i

src/cov_periodic_matern3_iso.s: src/cov_periodic_matern3_iso.cc.s

.PHONY : src/cov_periodic_matern3_iso.s

# target to generate assembly for a file
src/cov_periodic_matern3_iso.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_periodic_matern3_iso.cc.s
.PHONY : src/cov_periodic_matern3_iso.cc.s

src/cov_prod.o: src/cov_prod.cc.o

.PHONY : src/cov_prod.o

# target to build an object file
src/cov_prod.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_prod.cc.o
.PHONY : src/cov_prod.cc.o

src/cov_prod.i: src/cov_prod.cc.i

.PHONY : src/cov_prod.i

# target to preprocess a source file
src/cov_prod.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_prod.cc.i
.PHONY : src/cov_prod.cc.i

src/cov_prod.s: src/cov_prod.cc.s

.PHONY : src/cov_prod.s

# target to generate assembly for a file
src/cov_prod.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_prod.cc.s
.PHONY : src/cov_prod.cc.s

src/cov_rq_iso.o: src/cov_rq_iso.cc.o

.PHONY : src/cov_rq_iso.o

# target to build an object file
src/cov_rq_iso.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_rq_iso.cc.o
.PHONY : src/cov_rq_iso.cc.o

src/cov_rq_iso.i: src/cov_rq_iso.cc.i

.PHONY : src/cov_rq_iso.i

# target to preprocess a source file
src/cov_rq_iso.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_rq_iso.cc.i
.PHONY : src/cov_rq_iso.cc.i

src/cov_rq_iso.s: src/cov_rq_iso.cc.s

.PHONY : src/cov_rq_iso.s

# target to generate assembly for a file
src/cov_rq_iso.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_rq_iso.cc.s
.PHONY : src/cov_rq_iso.cc.s

src/cov_se_ard.o: src/cov_se_ard.cc.o

.PHONY : src/cov_se_ard.o

# target to build an object file
src/cov_se_ard.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_ard.cc.o
.PHONY : src/cov_se_ard.cc.o

src/cov_se_ard.i: src/cov_se_ard.cc.i

.PHONY : src/cov_se_ard.i

# target to preprocess a source file
src/cov_se_ard.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_ard.cc.i
.PHONY : src/cov_se_ard.cc.i

src/cov_se_ard.s: src/cov_se_ard.cc.s

.PHONY : src/cov_se_ard.s

# target to generate assembly for a file
src/cov_se_ard.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_ard.cc.s
.PHONY : src/cov_se_ard.cc.s

src/cov_se_iso.o: src/cov_se_iso.cc.o

.PHONY : src/cov_se_iso.o

# target to build an object file
src/cov_se_iso.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_iso.cc.o
.PHONY : src/cov_se_iso.cc.o

src/cov_se_iso.i: src/cov_se_iso.cc.i

.PHONY : src/cov_se_iso.i

# target to preprocess a source file
src/cov_se_iso.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_iso.cc.i
.PHONY : src/cov_se_iso.cc.i

src/cov_se_iso.s: src/cov_se_iso.cc.s

.PHONY : src/cov_se_iso.s

# target to generate assembly for a file
src/cov_se_iso.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_se_iso.cc.s
.PHONY : src/cov_se_iso.cc.s

src/cov_sum.o: src/cov_sum.cc.o

.PHONY : src/cov_sum.o

# target to build an object file
src/cov_sum.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_sum.cc.o
.PHONY : src/cov_sum.cc.o

src/cov_sum.i: src/cov_sum.cc.i

.PHONY : src/cov_sum.i

# target to preprocess a source file
src/cov_sum.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_sum.cc.i
.PHONY : src/cov_sum.cc.i

src/cov_sum.s: src/cov_sum.cc.s

.PHONY : src/cov_sum.s

# target to generate assembly for a file
src/cov_sum.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/cov_sum.cc.s
.PHONY : src/cov_sum.cc.s

src/gp.o: src/gp.cc.o

.PHONY : src/gp.o

# target to build an object file
src/gp.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp.cc.o
.PHONY : src/gp.cc.o

src/gp.i: src/gp.cc.i

.PHONY : src/gp.i

# target to preprocess a source file
src/gp.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp.cc.i
.PHONY : src/gp.cc.i

src/gp.s: src/gp.cc.s

.PHONY : src/gp.s

# target to generate assembly for a file
src/gp.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp.cc.s
.PHONY : src/gp.cc.s

src/gp_utils.o: src/gp_utils.cc.o

.PHONY : src/gp_utils.o

# target to build an object file
src/gp_utils.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp_utils.cc.o
.PHONY : src/gp_utils.cc.o

src/gp_utils.i: src/gp_utils.cc.i

.PHONY : src/gp_utils.i

# target to preprocess a source file
src/gp_utils.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp_utils.cc.i
.PHONY : src/gp_utils.cc.i

src/gp_utils.s: src/gp_utils.cc.s

.PHONY : src/gp_utils.s

# target to generate assembly for a file
src/gp_utils.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/gp_utils.cc.s
.PHONY : src/gp_utils.cc.s

src/input_dim_filter.o: src/input_dim_filter.cc.o

.PHONY : src/input_dim_filter.o

# target to build an object file
src/input_dim_filter.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/input_dim_filter.cc.o
.PHONY : src/input_dim_filter.cc.o

src/input_dim_filter.i: src/input_dim_filter.cc.i

.PHONY : src/input_dim_filter.i

# target to preprocess a source file
src/input_dim_filter.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/input_dim_filter.cc.i
.PHONY : src/input_dim_filter.cc.i

src/input_dim_filter.s: src/input_dim_filter.cc.s

.PHONY : src/input_dim_filter.s

# target to generate assembly for a file
src/input_dim_filter.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/input_dim_filter.cc.s
.PHONY : src/input_dim_filter.cc.s

src/rprop.o: src/rprop.cc.o

.PHONY : src/rprop.o

# target to build an object file
src/rprop.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/rprop.cc.o
.PHONY : src/rprop.cc.o

src/rprop.i: src/rprop.cc.i

.PHONY : src/rprop.i

# target to preprocess a source file
src/rprop.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/rprop.cc.i
.PHONY : src/rprop.cc.i

src/rprop.s: src/rprop.cc.s

.PHONY : src/rprop.s

# target to generate assembly for a file
src/rprop.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/rprop.cc.s
.PHONY : src/rprop.cc.s

src/sampleset.o: src/sampleset.cc.o

.PHONY : src/sampleset.o

# target to build an object file
src/sampleset.cc.o:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/sampleset.cc.o
.PHONY : src/sampleset.cc.o

src/sampleset.i: src/sampleset.cc.i

.PHONY : src/sampleset.i

# target to preprocess a source file
src/sampleset.cc.i:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/sampleset.cc.i
.PHONY : src/sampleset.cc.i

src/sampleset.s: src/sampleset.cc.s

.PHONY : src/sampleset.s

# target to generate assembly for a file
src/sampleset.cc.s:
	$(MAKE) -f CMakeFiles/gp.dir/build.make CMakeFiles/gp.dir/src/sampleset.cc.s
.PHONY : src/sampleset.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gp"
	@echo "... gp_calib"
	@echo "... gpdense"
	@echo "... gptest"
	@echo "... googletest"
	@echo "... src/cg.o"
	@echo "... src/cg.i"
	@echo "... src/cg.s"
	@echo "... src/cov.o"
	@echo "... src/cov.i"
	@echo "... src/cov.s"
	@echo "... src/cov_factory.o"
	@echo "... src/cov_factory.i"
	@echo "... src/cov_factory.s"
	@echo "... src/cov_linear_ard.o"
	@echo "... src/cov_linear_ard.i"
	@echo "... src/cov_linear_ard.s"
	@echo "... src/cov_linear_one.o"
	@echo "... src/cov_linear_one.i"
	@echo "... src/cov_linear_one.s"
	@echo "... src/cov_matern3_iso.o"
	@echo "... src/cov_matern3_iso.i"
	@echo "... src/cov_matern3_iso.s"
	@echo "... src/cov_matern5_iso.o"
	@echo "... src/cov_matern5_iso.i"
	@echo "... src/cov_matern5_iso.s"
	@echo "... src/cov_noise.o"
	@echo "... src/cov_noise.i"
	@echo "... src/cov_noise.s"
	@echo "... src/cov_periodic.o"
	@echo "... src/cov_periodic.i"
	@echo "... src/cov_periodic.s"
	@echo "... src/cov_periodic_matern3_iso.o"
	@echo "... src/cov_periodic_matern3_iso.i"
	@echo "... src/cov_periodic_matern3_iso.s"
	@echo "... src/cov_prod.o"
	@echo "... src/cov_prod.i"
	@echo "... src/cov_prod.s"
	@echo "... src/cov_rq_iso.o"
	@echo "... src/cov_rq_iso.i"
	@echo "... src/cov_rq_iso.s"
	@echo "... src/cov_se_ard.o"
	@echo "... src/cov_se_ard.i"
	@echo "... src/cov_se_ard.s"
	@echo "... src/cov_se_iso.o"
	@echo "... src/cov_se_iso.i"
	@echo "... src/cov_se_iso.s"
	@echo "... src/cov_sum.o"
	@echo "... src/cov_sum.i"
	@echo "... src/cov_sum.s"
	@echo "... src/gp.o"
	@echo "... src/gp.i"
	@echo "... src/gp.s"
	@echo "... src/gp_utils.o"
	@echo "... src/gp_utils.i"
	@echo "... src/gp_utils.s"
	@echo "... src/input_dim_filter.o"
	@echo "... src/input_dim_filter.i"
	@echo "... src/input_dim_filter.s"
	@echo "... src/rprop.o"
	@echo "... src/rprop.i"
	@echo "... src/rprop.s"
	@echo "... src/sampleset.o"
	@echo "... src/sampleset.i"
	@echo "... src/sampleset.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

